---
- hosts: localhost
  vars_files:
    - settings.yml
    - ['~/cloudbox/accounts.yml', '~/cloudbox/defaults/accounts.yml.default']
    - ['~/cloudbox/settings.yml', '~/cloudbox/defaults/settings.yml.default']
    - ['~/cloudbox/adv_settings.yml', '~/cloudbox/defaults/adv_settings.yml.default']
  roles:
  # Reqs
    - { role: settings, tags: ['always', 'settings'] }
    #- { role: sanity_check, tags: ['always', 'sanity_check'] }
    #- { role: pre_tasks, tags: ['pre_tasks'] }
  # Apps
    - { role: pre_tasks }
    - { role: myrole, tags: ['myrole'] }
    - { role: mkvtoolnix, tags: ['mkvtoolnix'] }
    - { role: flexget, tags: ['flexget'] }

